import "../App.css";

function PrivacyPolicy({ handlePolicyClose }) {
  return (
    <>
      <div className="alldisputemodal-container" onClick={handlePolicyClose}>
        <div className="alldispute-content">
          <div className="privacy-details">
            <div className="privacy-box">
              <h1>Nubeero Privacy Policy</h1>
              <div>
                <h3>1. Introduction</h3>
                <p>
                  Welcome to Nubeero Limited. Nubeero Limited (“us”, “we”, or “our”) operates <a href="https://www.nubeero.com">www.nubeero.com</a> (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to www.nubeero.com, and
                  explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in
                  accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Our Terms and Conditions (“Terms”) govern all use of our
                  Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).
                </p>
                <h3>2. Definitions</h3>
                <p>
                  ‘SERVICE’ means the www.nubeero.com website operated by Nubeero Limited. “PERSONAL DATA” means data about a living individual who can be identified from those data (or from those and other information either in our possession or
                  likely to come into our possession). “USAGE DATA” is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit). “COOKIES” are small files
                  stored on your device (computer or mobile device). DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal
                  data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data. “DATA PROCESSORS (OR SERVICE PROVIDERS)” means any natural or legal person who processes the data on behalf of the
                  Data Controller. We may use the services of various Service Providers in order to process your data more effectively. “DATA SUBJECT” is any living individual who is the subject of Personal Data. THE USER is the individual using our
                  Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                </p>
                <h3>3. Information Collection and Use</h3>
                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                <h3>4. Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>
                  We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”). This Usage Data may include information such as your computer’s Internet
                  Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When
                  you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use,
                  unique device identifiers and other diagnostic data.
                </p>

                <h4>Usage Data</h4>
                <p>
                  We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”). This Usage Data may include information such as your computer’s Internet
                  Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When
                  you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use,
                  unique device identifiers and other diagnostic data.
                </p>
                <h4>Location Data</h4>
                <p>
                  We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location
                  services when you use our Service at any time by way of your device settings.
                </p>
                <h4>Tracking Cookies Data</h4>
                <p>
                  We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent
                  to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your
                  browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
                <p>
                  Examples of Cookies we use:
                  <br />
                  <br />
                  i. Session Cookies: We use Session Cookies to operate our Service.
                  <br />
                  <br />
                  ii. Preference Cookies: We use Preference Cookies to remember your preferences and various settings. <br />
                  <br />
                  iii. Security Cookies: We use Security Cookies for security purposes.
                  <br />
                  <br /> iv. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
                </p>
                <h4>Other Data</h4>
                <p>
                  While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile),
                  details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other
                  taxpayer identification) number, office location and other data.
                </p>
                <h3>5. Use of Data</h3>
                <p>
                  Nubeero Limited uses the collected data for various purposes:
                  <br />
                  <br />
                  i. to provide and maintain our Service
                  <br />
                  <br />
                  ii. to notify you about changes to our Service;
                  <br />
                  <br />
                  iii. to allow you to participate in interactive features of our Service when you choose to do so;
                  <br />
                  <br />
                  iv. to provide customer support;
                  <br />
                  <br />
                  v. to gather analysis or valuable information so that we can improve our Service;
                  <br />
                  <br />
                  vi. to monitor the usage of our Service;
                  <br />
                  <br />
                  vii. to detect, prevent and address technical issues;
                  <br />
                  <br />
                  viii. to fulfil any other purpose for which you provide it;
                  <br />
                  <br />
                  ix. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
                  <br />
                  <br />
                  x. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;
                  <br />
                  <br />
                  xi. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to
                  receive such information;
                  <br />
                  <br />
                  xii. in any other way we may describe when you provide the information;
                  <br />
                  <br />
                  xiii. for any other purpose with your consent.
                </p>
                <h3>6. Retention of Data</h3>
                <p>
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example,
                  if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <br />
                <p>
                  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are
                  legally obligated to retain this data for longer time periods.
                </p>
                <h3>7. Transfer of Data</h3>
                <p>
                  Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from
                  those of your jurisdiction. If you are located outside Nigeria and choose to provide information to us, please note that we transfer the data, including Personal Data, to Nigeria and process it there. Your consent to this Privacy
                  Policy followed by your submission of such information represents your agreement to that transfer. Nubeero Limited will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this
                  Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>
                <h3>8. Disclosure of Data</h3>
                <p>
                  We may disclose personal information that we collect, or you provide:
                  <br />
                  <br />
                  i. Disclosure for Law Enforcement: Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                  <br />
                  <br />
                  ii. Business Transaction: If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
                  <br />
                  <br />
                  iii. Other cases: We may disclose your information also:
                  <br />
                  <br />
                  • to our subsidiaries and affiliates;
                  <br />
                  <br />
                  • to contractors, service providers, and other third parties we use to support our business;
                  <br />
                  <br />
                  • to fulfill the purpose for which you provided it;
                  <br />
                  <br />
                  • for the purpose of including your company’s logo on our website;
                  <br />
                  <br />
                  • for any other purpose disclosed by us when you provide the information;
                  <br />
                  <br />
                  • with your consent in any other cases;
                  <br />
                  <br />• if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
                </p>
                <h3>9. Security of Data</h3>
                <p>
                  The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal
                  Data, we cannot guarantee its absolute security.
                </p>
                <br />
                <br />
                <br />
                <h3>10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>
                <br />
                <p>
                  If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of
                  your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at info@nubeeroi.com. In certain circumstances, you have the following data
                  protection rights:
                </p>
                <br />
                <br />
                <p>
                  i. the right to access, update or to delete the information we have on you <br />
                  <br />
                  ii. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete; <br />
                  <br />
                  iii. the right to object. You have the right to object to our processing of your Personal Data; <br />
                  <br />
                  iv. the right of restriction. You have the right to request that we restrict the processing of your personal information; <br />
                  <br />
                  v. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format; <br />
                  <br />
                  vi. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information; <br />
                  <br />
                  Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data. You have the right to complain to a Data Protection Authority
                  about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                </p>
                <br />
                <h3>11. Your Data Protection Rights under the Nigerian Privacy Laws</h3>
                <p>
                  This Privacy Policy is made pursuant to the Nigeria Data Protection Regulation (2019) and other relevant Nigerian laws, regulations or international conventions applicable to Nigeria. Where any provision of this Policy is deemed
                  inconsistent with a law, regulation or convention, such provision shall be subject to the overriding law, regulation or convention. If you are a Nigerian resident, you are entitled to learn what data we collect about you, ask to
                  delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
                  <br />
                  <br />
                  i. What personal information we have about you. If you make this request, we will return to you:
                  <br />
                  <br />• The categories of personal information we have collected about you.
                  <br />
                  <br />• The categories of sources from which we collect your personal information.
                  <br />
                  <br />• The business or commercial purpose for collecting or selling your personal information.
                  <br />
                  <br />• The categories of third parties with whom we share personal information.
                  <br />
                  <br />• The specific pieces of personal information we have collected about you.
                  <br />
                  <br />• A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.
                  <br />
                  <br />• A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with. Please note, you are entitled to ask us to provide you with this
                  information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
                  <br />
                  <br />
                  ii. To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some
                  cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
                  <br />
                  <br />
                  iii. To stop selling your personal information. We don’t sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. You are the only owner of
                  your Personal Data and can request disclosure or deletion at any time. If you submit a request to stop selling your personal information, we will stop making such transfers. Please note, if you ask us to delete or stop selling your
                  data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will
                  discriminate against you for exercising your rights. To exercise your Nigerian data protection rights described above, please send your request(s) by email: info@nubeero.com.
                </p>
                <h3>12. Service Providers</h3>

                <p>
                  We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used. These third
                  parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. We do not ensure that the information on this website is correct, we do not
                  warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.
                </p>
                <br />
                <h3>13. Analytics</h3>

                <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
                <h3>14. CI/CD tools</h3>

                <p>We may use third-party Service Providers to automate the development process of our Service.</p>
                <br />
                <h3>15. Behavioral Remarketing</h3>

                <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>
                <br />
                <h3>16. Links to Other Sites</h3>

                <p>
                  Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
                  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
                <br />
                <h3>17. Children’s Privacy</h3>

                <p>
                  Our Services are not intended for use by children under the age of 18 (“Child” or “Children”). We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us
                  with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
                <br />
                <h3>19. Changes to This Privacy Policy</h3>

                <p>
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change
                  becoming effective and update “effective date” at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this
                  page.
                </p>
                <br />
                <h3>20. Contact Us</h3>

                <p>If you have any questions about this Privacy Policy, please contact us by email: info@nubeero.com.</p>
                <p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default PrivacyPolicy;
